include ../../SciEng.mkdefs

FILES_WITH_MAIN	= average.C sizet.C tTuplize.C

ALL_FILES = Array2d-with-dim.C ArrayErr.C ArraynT.C ArrayxD.C average.C rigid.C sizet.C tTuplize.C

all:	$(ALL_FILES:.C=.o) $(FILES_WITH_MAIN:.C=)
