include ../../SciEng.mkdefs

FILES_WITH_MAIN	= IteratorFrobenius.C tCollect.C tConcreteMax.C tDiagonal.C while.C

ALL_FILES = IteratorFrobenius.C bad-assign.C tCollect.C tConcreteMax.C tDiagonal.C while.C

all:	$(ALL_FILES:.C=.o) $(FILES_WITH_MAIN:.C=)
