include ../../SciEng.mkdefs

FILES_WITH_MAIN	= AtwoodsMachine.C lin-frac.C tASGArray.C tGroupD3.C tIntMod5.C tSpaceVector.C

ALL_FILES = AtwoodsMachine.C global-category-template.C global-function-template.C lin-frac.C tASGArray.C tGroupD3.C tIntMod5.C tSpaceVector.C

all:	$(ALL_FILES:.C=.o) $(FILES_WITH_MAIN:.C=)
