include ../../SciEng.mkdefs

FILES_WITH_MAIN	= Bool-examples.C arrayAssign.C demoFal.C demoList.C

ALL_FILES = Bool-examples.C Circle.C CmplxFlt.C SimpleFloatArray.C UsePoint.C ambig-convert.C ambig-convert2.C ambig-convert3.C arrayAssign.C cmplx.C cmplx1.C cmplx2.C dcl-syntax.C demoFal.C demoList.C friend.C mult-assign.C

all:	$(ALL_FILES:.C=.o) $(FILES_WITH_MAIN:.C=)
