include ../../SciEng.mkdefs

FILES_WITH_MAIN	= exceptionLeak.C exceptionNoLeak.C tCounted.C tMolecule.C

ALL_FILES = CopiedObjPtrDemo.C badCall.C equiv-dcls.C exceptionLeak.C exceptionNoLeak.C macro.C tCounted.C tMolecule.C

all:	$(ALL_FILES:.C=.o) $(FILES_WITH_MAIN:.C=)
